// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
)

type Activity struct {
	ID        int32          `json:"id"`
	Url       string         `json:"url"`
	Method    sql.NullString `json:"method"`
	UrlRegex  string         `json:"url_regex"`
	CreatedAt sql.NullTime   `json:"created_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Permission struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type PermissionActivity struct {
	PermissionID int32        `json:"permission_id"`
	ActivityID   int32        `json:"activity_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Role struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int32        `json:"role_id"`
	PermissionID int32        `json:"permission_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type UserAccount struct {
	ID                     int32          `json:"id"`
	FirstName              sql.NullString `json:"first_name"`
	LastName               sql.NullString `json:"last_name"`
	FullName               sql.NullString `json:"full_name"`
	Address                sql.NullString `json:"address"`
	Email                  string         `json:"email"`
	Password               string         `json:"password"`
	PhoneNumber            sql.NullString `json:"phone_number"`
	AcceptsMarketing       bool           `json:"accepts_marketing"`
	CodeVerifyEmail        sql.NullInt32  `json:"code_verify_email"`
	VerifyEmail            sql.NullBool   `json:"verify_email"`
	PasswordCost           sql.NullString `json:"password_cost"`
	RegistrationTime       sql.NullTime   `json:"registration_time"`
	EmailConfirmationToken sql.NullString `json:"email_confirmation_token"`
	UserStatus             sql.NullInt32  `json:"user_status"`
	PasswordReminderToken  sql.NullString `json:"password_reminder_token"`
	PasswordReminderExpire sql.NullTime   `json:"password_reminder_expire"`
	CreatedAt              sql.NullTime   `json:"created_at"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
}

type UserRole struct {
	UserID    int64        `json:"user_id"`
	RoleID    int32        `json:"role_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
